# Where things are
source:       .
destination:  ./_site
plugins_dir:      ./_plugins
layouts_dir:      ./_layouts
paginate:     8
gems: [jekyll-paginate]

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  rouge
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: Coding daily
description: Records coding daily for mmaoyu.
keywords: mmaoyu coding
url: https://mmaoyu.github.io
feed: /atom.xml
favicon: https://avatars0.githubusercontent.com/u/4112583
# favicon: https://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: mmaoyu
    email: wupiaoyu61@gmail.com
    imageLink: https://avatars0.githubusercontent.com/u/4112583
    simpleIntro: Stay hungry,Stay foolish.
    detailIntro:
      <p></p>
      <p></p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-github-alt
    url: https://github.com/mmaoyu

#Links
customLinks:
  - item:
    - text: fred
      url: https://kenshinji.me/
    - text: laixintao
      url: https://www.kawabangga.com  
    message: Blogs
  - item:
    - text: Font Awesome
      url: https://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: https://www.google.com/fonts/
    - text: jQuery
      url: https://jquery.com/
    message: Others

#googleAnaly, your id link UA-12345678-X
#googleAnaly:
#  config: true
# id: 

#comment config
#disqus:
#  config: false
#  id: 

